CREATE TABLE IF NOT EXISTS "Batting" (
"playerID" TEXT,
  "yearID" INTEGER,
  "stint" INTEGER,
  "teamID" TEXT,
  "lgID" TEXT,
  "G" INTEGER,
  "AB" INTEGER,
  "R" INTEGER,
  "H" INTEGER,
  "2B" INTEGER,
  "3B" INTEGER,
  "HR" INTEGER,
  "RBI" REAL,
  "SB" REAL,
  "CS" REAL,
  "BB" INTEGER,
  "SO" REAL,
  "IBB" REAL,
  "HBP" REAL,
  "SH" REAL,
  "SF" REAL,
  "GIDP" REAL
);
CREATE TABLE IF NOT EXISTS "FieldingPost" (
"playerID" TEXT,
  "yearID" INTEGER,
  "teamID" TEXT,
  "lgID" TEXT,
  "round" TEXT,
  "POS" TEXT,
  "G" INTEGER,
  "GS" REAL,
  "InnOuts" INTEGER,
  "PO" INTEGER,
  "A" INTEGER,
  "E" INTEGER,
  "DP" INTEGER,
  "TP" REAL,
  "PB" REAL,
  "SB" REAL,
  "CS" REAL
);
CREATE TABLE IF NOT EXISTS "PitchingPost" (
"playerID" TEXT,
  "yearID" INTEGER,
  "round" TEXT,
  "teamID" TEXT,
  "lgID" TEXT,
  "W" INTEGER,
  "L" INTEGER,
  "G" INTEGER,
  "GS" INTEGER,
  "CG" INTEGER,
  "SHO" INTEGER,
  "SV" INTEGER,
  "IPouts" INTEGER,
  "H" INTEGER,
  "ER" INTEGER,
  "HR" INTEGER,
  "BB" INTEGER,
  "SO" INTEGER,
  "BAOpp" REAL,
  "ERA" REAL,
  "IBB" REAL,
  "WP" REAL,
  "HBP" REAL,
  "BK" REAL,
  "BFP" REAL,
  "GF" REAL,
  "R" INTEGER,
  "SH" REAL,
  "SF" REAL,
  "GIDP" REAL
);
CREATE TABLE IF NOT EXISTS "Schools" (
"schoolID" TEXT,
  "name_full" TEXT,
  "city" TEXT,
  "state" TEXT,
  "country" TEXT
);
CREATE TABLE IF NOT EXISTS "FieldingOFsplit" (
"playerID" TEXT,
  "yearID" INTEGER,
  "stint" INTEGER,
  "teamID" TEXT,
  "lgID" TEXT,
  "POS" TEXT,
  "G" INTEGER,
  "GS" REAL,
  "InnOuts" INTEGER,
  "PO" REAL,
  "A" REAL,
  "E" REAL,
  "DP" REAL,
  "PB" REAL,
  "WP" REAL,
  "SB" REAL,
  "CS" REAL,
  "ZR" REAL
);
CREATE TABLE IF NOT EXISTS "HallOfFame" (
"playerID" TEXT,
  "yearid" INTEGER,
  "votedBy" TEXT,
  "ballots" REAL,
  "needed" REAL,
  "votes" REAL,
  "inducted" TEXT,
  "category" TEXT,
  "needed_note" TEXT
);
CREATE TABLE IF NOT EXISTS "Fielding" (
"playerID" TEXT,
  "yearID" INTEGER,
  "stint" INTEGER,
  "teamID" TEXT,
  "lgID" TEXT,
  "POS" TEXT,
  "G" INTEGER,
  "GS" REAL,
  "InnOuts" REAL,
  "PO" REAL,
  "A" REAL,
  "E" REAL,
  "DP" REAL,
  "PB" REAL,
  "WP" REAL,
  "SB" REAL,
  "CS" REAL,
  "ZR" REAL
);
CREATE TABLE IF NOT EXISTS "Managers" (
"playerID" TEXT,
  "yearID" INTEGER,
  "teamID" TEXT,
  "lgID" TEXT,
  "inseason" INTEGER,
  "G" INTEGER,
  "W" INTEGER,
  "L" INTEGER,
  "rank" INTEGER,
  "plyrMgr" TEXT
);
CREATE TABLE IF NOT EXISTS "CollegePlaying" (
"playerID" TEXT,
  "schoolID" TEXT,
  "yearID" REAL
);
CREATE TABLE IF NOT EXISTS "People" (
"ID" INTEGER,
  "playerID" TEXT,
  "birthYear" REAL,
  "birthMonth" REAL,
  "birthDay" REAL,
  "birthCity" TEXT,
  "birthCountry" TEXT,
  "birthState" TEXT,
  "deathYear" REAL,
  "deathMonth" REAL,
  "deathDay" REAL,
  "deathCountry" TEXT,
  "deathState" TEXT,
  "deathCity" TEXT,
  "nameFirst" TEXT,
  "nameLast" TEXT,
  "nameGiven" TEXT,
  "weight" REAL,
  "height" REAL,
  "bats" TEXT,
  "throws" TEXT,
  "debut" TEXT,
  "bbrefID" TEXT,
  "finalGame" TEXT,
  "retroID" TEXT
);
CREATE TABLE IF NOT EXISTS "AwardsPlayers" (
"playerID" TEXT,
  "awardID" TEXT,
  "yearID" INTEGER,
  "lgID" TEXT,
  "tie" TEXT,
  "notes" TEXT
);
CREATE TABLE IF NOT EXISTS "FieldingOF" (
"playerID" TEXT,
  "yearID" INTEGER,
  "stint" INTEGER,
  "Glf" REAL,
  "Gcf" REAL,
  "Grf" REAL
);
CREATE TABLE IF NOT EXISTS "AwardsManagers" (
"playerID" TEXT,
  "awardID" TEXT,
  "yearID" INTEGER,
  "lgID" TEXT,
  "tie" TEXT,
  "notes" TEXT
);
CREATE TABLE IF NOT EXISTS "Teams" (
"yearID" INTEGER,
  "lgID" TEXT,
  "teamID" TEXT,
  "franchID" TEXT,
  "divID" TEXT,
  "Rank" INTEGER,
  "G" INTEGER,
  "Ghome" REAL,
  "W" INTEGER,
  "L" INTEGER,
  "DivWin" TEXT,
  "WCWin" TEXT,
  "LgWin" TEXT,
  "WSWin" TEXT,
  "R" REAL,
  "AB" REAL,
  "H" REAL,
  "2B" REAL,
  "3B" REAL,
  "HR" REAL,
  "BB" REAL,
  "SO" REAL,
  "SB" REAL,
  "CS" REAL,
  "HBP" REAL,
  "SF" REAL,
  "RA" REAL,
  "ER" REAL,
  "ERA" REAL,
  "CG" REAL,
  "SHO" REAL,
  "SV" REAL,
  "IPouts" REAL,
  "HA" REAL,
  "HRA" REAL,
  "BBA" REAL,
  "SOA" REAL,
  "E" REAL,
  "DP" REAL,
  "FP" REAL,
  "name" TEXT,
  "park" TEXT,
  "attendance" REAL,
  "BPF" REAL,
  "PPF" REAL,
  "teamIDBR" TEXT,
  "teamIDlahman45" TEXT,
  "teamIDretro" TEXT
);
CREATE TABLE IF NOT EXISTS "Pitching" (
"playerID" TEXT,
  "yearID" INTEGER,
  "stint" INTEGER,
  "teamID" TEXT,
  "lgID" TEXT,
  "W" INTEGER,
  "L" INTEGER,
  "G" INTEGER,
  "GS" INTEGER,
  "CG" INTEGER,
  "SHO" INTEGER,
  "SV" INTEGER,
  "IPouts" INTEGER,
  "H" INTEGER,
  "ER" INTEGER,
  "HR" REAL,
  "BB" INTEGER,
  "SO" INTEGER,
  "BAOpp" REAL,
  "ERA" REAL,
  "IBB" REAL,
  "WP" REAL,
  "HBP" REAL,
  "BK" REAL,
  "BFP" REAL,
  "GF" REAL,
  "R" INTEGER,
  "SH" REAL,
  "SF" REAL,
  "GIDP" REAL
);
CREATE TABLE IF NOT EXISTS "Appearances" (
"yearID" INTEGER,
  "teamID" TEXT,
  "lgID" TEXT,
  "playerID" TEXT,
  "G_all" INTEGER,
  "GS" REAL,
  "G_batting" REAL,
  "G_defense" REAL,
  "G_p" REAL,
  "G_c" REAL,
  "G_1b" REAL,
  "G_2b" REAL,
  "G_3b" REAL,
  "G_ss" REAL,
  "G_lf" REAL,
  "G_cf" REAL,
  "G_rf" REAL,
  "G_of" REAL,
  "G_dh" REAL,
  "G_ph" REAL,
  "G_pr" REAL
);
CREATE TABLE IF NOT EXISTS "HomeGames" (
"yearkey" INTEGER,
  "leaguekey" TEXT,
  "teamkey" TEXT,
  "parkkey" TEXT,
  "spanfirst" TEXT,
  "spanlast" TEXT,
  "games" INTEGER,
  "openings" INTEGER,
  "attendance" INTEGER
);
CREATE TABLE IF NOT EXISTS "AwardsShareManagers" (
"awardID" TEXT,
  "yearID" INTEGER,
  "lgID" TEXT,
  "playerID" TEXT,
  "pointsWon" INTEGER,
  "pointsMax" INTEGER,
  "votesFirst" INTEGER
);
CREATE TABLE IF NOT EXISTS "TeamsFranchises" (
"franchID" TEXT,
  "franchName" TEXT,
  "active" TEXT,
  "NAassoc" TEXT
);
CREATE TABLE IF NOT EXISTS "Parks" (
"ID" INTEGER,
  "parkalias" TEXT,
  "parkkey" TEXT,
  "parkname" TEXT,
  "city" TEXT,
  "state" TEXT,
  "country" TEXT
);
CREATE TABLE IF NOT EXISTS "ManagersHalf" (
"playerID" TEXT,
  "yearID" INTEGER,
  "teamID" TEXT,
  "lgID" TEXT,
  "inseason" INTEGER,
  "half" INTEGER,
  "G" INTEGER,
  "W" INTEGER,
  "L" INTEGER,
  "rank" INTEGER
);
CREATE TABLE IF NOT EXISTS "TeamsHalf" (
"yearID" INTEGER,
  "lgID" TEXT,
  "teamID" TEXT,
  "Half" INTEGER,
  "divID" TEXT,
  "DivWin" TEXT,
  "Rank" INTEGER,
  "G" REAL,
  "W" REAL,
  "L" REAL
);
CREATE TABLE IF NOT EXISTS "AwardsSharePlayers" (
"awardID" TEXT,
  "yearID" INTEGER,
  "lgID" TEXT,
  "playerID" TEXT,
  "pointsWon" INTEGER,
  "pointsMax" INTEGER,
  "votesFirst" REAL
);
CREATE TABLE IF NOT EXISTS "BattingPost" (
"yearID" INTEGER,
  "round" TEXT,
  "playerID" TEXT,
  "teamID" TEXT,
  "lgID" TEXT,
  "G" INTEGER,
  "AB" INTEGER,
  "R" INTEGER,
  "H" INTEGER,
  "2B" INTEGER,
  "3B" INTEGER,
  "HR" INTEGER,
  "RBI" INTEGER,
  "SB" INTEGER,
  "CS" REAL,
  "BB" INTEGER,
  "SO" REAL,
  "IBB" REAL,
  "HBP" REAL,
  "SH" REAL,
  "SF" REAL,
  "GIDP" REAL
);
CREATE TABLE IF NOT EXISTS "AllstarFull" (
"playerID" TEXT,
  "yearID" INTEGER,
  "gameNum" REAL,
  "gameID" TEXT,
  "teamID" TEXT,
  "lgID" TEXT,
  "GP" INTEGER,
  "startingPos" TEXT
);
CREATE TABLE IF NOT EXISTS "Salaries" (
"yearID" INTEGER,
  "teamID" TEXT,
  "lgID" TEXT,
  "playerID" TEXT,
  "salary" INTEGER
);
CREATE TABLE IF NOT EXISTS "SeriesPost" (
"yearID" INTEGER,
  "round" TEXT,
  "teamIDwinner" TEXT,
  "lgIDwinner" TEXT,
  "teamIDloser" TEXT,
  "lgIDloser" TEXT,
  "wins" INTEGER,
  "losses" INTEGER,
  "ties" INTEGER
);
